### ISSUE TITLE
`text` could/should be as children

### ISSUE THREAD

**Issue by kud** [alexandersmanning/read-more-react#12]

**Comment by alexandersmanning** [comment]
Let me think it through and look into it.

**Comment by kud** [comment]
Thanks! :)

**Comment by caseyjkey** [comment]
> Let me think it through and look into it.

This would help for allowing for html, because my text I'm trying to add contains bullets and breaks.

**Comment by alexandersmanning** [comment]
I am going to avoid this, as it adds a lot of unnecessary complexity (do I only grab from `<text>` tags?, do I concat each tags text, etc.). Furthermore grabbing text from children is considered an anti-pattern by the react team: https://github.com/facebook/react/issues/9255
