### ISSUE TITLE
Allow 'readMoreText' to accept react components rather than strings

### ISSUE THREAD

**Issue by erwinleonardy** [alexandersmanning/read-more-react#18]
Hi guys!

I am wondering if it is possible for you guys to let 'readMoreText' accept react components as props rather than strings?

Although it does allow me to pass a react element as the 'readMoreText' props, it is still showing me this error:
> index.js:1 Warning: Failed prop type: Invalid prop `readMoreText` of type `object` supplied to `ReadMoreReact`, expected `string`.

Thank You!

**Comment by alexandersmanning** [comment]
This sadly cannot work for this type of component, please see: https://github.com/alexandersmanning/read-more-react/issues/12#issuecomment-578459557

If all you care about is height of the component, it is trivial for you to implement this with CSS/in-line styling, in which a read button changes the height (in px or %)/removes in when clicked. I am considering making a secondary component to do so, given that it has been requested a few times.
