### ISSUE TITLE
"Read More" Text

### ISSUE THREAD

**Issue by moparlakci** [alexandersmanning/read-more-react#5]
Ability to change the Read More text to another language through props?

**Comment by alexandersmanning** [comment]
I like the idea a lot. Let me see if I can do it quickly.

**Comment by alexandersmanning** [comment]
@moparlakci Just updated, you can find version 1.07 on npm! Text goes in the `readMoreText` prop.

```javascript
<ReadMoreReact text={yourTextHere}
				min={minimumLength}
				ideal={idealLength}
				max={maxLength}
				readMoreText="click here to read more"/>
```
