### ISSUE TITLE
text not visible in source in case of SSR

### ISSUE THREAD

**Issue by puneetsngh** [alexandersmanning/read-more-react#6]
I am doing Server Side rendering of the page, the text other than this have no issue but the text wrap inside this component not visible in 'view page source' and ultimately hamper SEO. any solutions?

**Comment by alexandersmanning** [comment]
Yes, it is going to be a small re-write of the component, but I can fix it in the next few days.

**Comment by alexandersmanning** [comment]
Put in a fix that can be found in version 1.08.

**Comment by puneetsngh** [comment]
Yes, you have fixed the part which wouldn’t be visible. But in case of SSR, nothing render from read-more-react component. This is because of the fact that you are updating state in componentDidMount which is rendered on client not on server. Wouldn’t it be better if you update state in componentWillMount or getDerivedStateFromProps (depending on the version of react you are using) ?

**Comment by puneetsngh** [comment]
@alexandersmanning check this PR https://github.com/alexandersmanning/read-more-react/pull/7
